### PR TITLE
Use bitflags for StatusField

### PR DESCRIPTION
**Pull request by SarthakSingh31**
Hello, I am from discord. I saw the post of you asking for code review. I have some suggestions. The first of them is in this pr.

### CODE REVIEW

**Comment by maebli** [comment]
Thank you for the PR 👍  I'm trying to use any libs, could you adjust the PR to not use dependency bitflags?

**Comment by SarthakSingh31** [comment]
It is going to be hard to develop a quality rust crate without depending on some foundational crates in the rust ecosystem. Why do you not want to depend on 3rd party crates? Even the rust compiler depends on `bitflags`.

**Comment by maebli** [comment]
> It is going to be hard to develop a quality rust crate without depending on some foundational crates in the rust ecosystem. Why do you not want to depend on 3rd party crates? Even the rust compiler depends on `bitflags`.

The idea is to have it run on embedded targets https://docs.rust-embedded.org/book/intro/no-std.html

**Comment by maebli** [comment]
Ah OK I learnt something then, how can we enforce that only no-std libs are used?

**Comment by SarthakSingh31** [comment]
@maebli can we speak over discord or some other platform? I have messaged you.

**Pull request merged**
